### ISSUE TITLE
Incorrect git clone command in README

### ISSUE THREAD

**Issue by Chieftl** [wxs77577/rest-admin#11]
`git clone git@github.com:wxs77577/rest-admin.git` command not working as expected, error is throwed:
`Permission denied (publickey).
fatal: Could not read from remote repository.`

But this is working ok:
`git clone https://github.com/wxs77577/rest-admin.git`

Please update README.

**Comment by wxs77577** [comment]
please check this post:

https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey
