### ISSUE TITLE
npm run serve  error

### ISSUE THREAD

**Issue by johnson7788** [wxs77577/rest-admin#13]
all create link can't access
http://localhost:8080/#/products/create    
http://localhost:8080/#/categories/create

**Comment by johnson7788** [comment]
DataTable.vue   find an error
 :to="'/rest/' 

          <b-btn class="mr-2" :to="'/rest/' + resourceUri + '/create'" variant="secondary" v-if="_.get(actions,'toolbar.create') !== false">

**Comment by wxs77577** [comment]
Have these problems been solved?

**Comment by wxs77577** [comment]
Closed since no response.
