### ISSUE TITLE
Build for production error: Unexpected token: name (code) [./node_modules/vue-snotify/vue-snotify.esm.js:104

### ISSUE THREAD

**Issue by metrey** [wxs77577/rest-admin#14]
Build for production with `npm run-script build` got error

`
ERROR in static/js/vendor.js from UglifyJs
Unexpected token: name (code) [./node_modules/vue-snotify/vue-snotify.esm.js:104,0][static/js/vendor.js:27544,12]

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-dev@0.9.1 build: `node build/build.js`
npm ERR! Exit status 1
`

I did try around this: https://github.com/artemsky/vue-snotify/issues/14 but not work at all.

My environment:
- nodejs v9.5.0
- npm v5.10.0
- Windows 10

Anyone face or any solution?

**Comment by metrey** [comment]
I comment out the plugin UglifyJs 

`// UglifyJs do not support ES6+, you can also use babel-minify for better treeshaking: https://github.com/babel/minify
    // new webpack.optimize.UglifyJsPlugin({`

**Comment by wxs77577** [comment]
Sorry but it seems not the problem of rest-admin.

**Comment by wxs77577** [comment]
Closed temporary.
