### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by lixaotec** [wxs77577/rest-admin#15]
Dear Fellows,

I couldnt use the table component, it renders the table header, but with neighter action buttons  (for add) nor data row.

Could you provide some working example?

Thanks

**Comment by wxs77577** [comment]
Please follow the usage guide and provide detailed error logs from console.

**Comment by lixaotec** [comment]
Dear @wxs77577 , thx for the quickly response.

I don´t think its a bug at all, I see no errors in console.

I am just curious to see how it works, but I´m not too experienced

I used the example field steps, and sent a shot down there:

```
  "steps": { "type": "array", "group": "Steps", is_table:true, "fields": {
      "name": { "label": "Name" },
      "date": { "label": "date", type: 'date'}
    },
```

![image](https://user-images.githubusercontent.com/40803484/49085465-38838080-f239-11e8-895e-df5e7dfb6bbe.png)

Just wondering if you have more examples or tell me what is wrong with my code

**Comment by lixaotec** [comment]
Btw dear @wxs77577 ,

Do you have any example of using vue-select with relations like in a order - products scenario?

I´m struggling to acocmplish that, with a select2 component with remote filter/search to find products, and to add multiple in a order with custom fields, like qtd.

Can you provide me tips in order to accomplish it with rest-admin?

Thanks

**Comment by wxs77577** [comment]
The latest demo api has been updated, please refer to: https://github.com/wxs77577/rest-admin/blob/master/api/index.js#L177
