### ISSUE TITLE
Missing Peer Dependency after last commit (jquery and ajv)

### ISSUE THREAD

**Issue by lixaotec** [wxs77577/rest-admin#17]
Dear @wxs77577 ,

After last commit I found this warn of missing peers. Perhaps adding to package.json ?

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

Thanks

**Comment by wxs77577** [comment]
Just ignore it, jquery is not required.
