### ISSUE TITLE
v-for index as key on <transition-group> children

### ISSUE THREAD

**Issue by lixaotec** [wxs77577/rest-admin#18]
Dear @wxs77577,

I found that after last commit this issue happened.

It affects the field rendering for edit, (it doens´t render them)

https://github.com/wxs77577/rest-admin/blob/f13b69b6585124d492e35c31702b0f79e49b4925/src/components/FormField.vue#L165

I think you should att anoter key id `:key="`item_${i}`"`

Thanks

**Comment by wxs77577** [comment]
I will fix that.
