### ISSUE TITLE
_actions addon tag vs Envelope Improve

### ISSUE THREAD

**Issue by lixaotec** [wxs77577/rest-admin#19]
Dear @wxs77577 ,

Just wondering, why using addons tags (underscored) at Fields description, instead of aggregating new patterns on the Envelop?

```
I think it would be a cleaner way to do like:
{
 data: [],
 fields: {
...
},
actions: {}
}
```

Or something like that, perhaps there is a standard or more widely use pattern?!

What do you think?

Thanks

**Comment by wxs77577** [comment]
please check the docs of bootstrap-vue table

**Comment by lixaotec** [comment]
Thanks.

I´ll take a better look there.

What about the endpoints /grid /view /form , did you choose by any reference?
I´ve been looking to some standards or best pratices on that, to have a more interoperable system.

Thanks again.

**Comment by wxs77577** [comment]
No, so I’m trying to make them customable.
