### ISSUE TITLE
CustomTable Concepts

### ISSUE THREAD

**Issue by lixaotec** [wxs77577/rest-admin#21]
Dear @wxs77577 ,

Would you explain a little bit of CustomTable vs DataTable components?

Why their code seems to be very different, and what it enables against DataTable?

Thank you very much

**Comment by lixaotec** [comment]
Just find out that CustomTable is some kind of work in progress.. is that right?

**Comment by wxs77577** [comment]
CustomTable is the better Version of DataTable, but my project use a different layout , so now DataTable is used for my personal project only,I use it by define grid_style:2 in site config api.
