### ISSUE TITLE
Is it possible to configure to use with WordPress rest api

### ISSUE THREAD

**Issue by aurovrata** [wxs77577/rest-admin#22]
Looking at the readme its not quite clear if the api can be configured to load from a WordPress db

**Comment by wxs77577** [comment]
You need to write a server by yourself.

**Comment by aurovrata** [comment]
Understood.  Could you give me a few pointers as to which files would need to be changed

**Comment by wxs77577** [comment]
Once you finished your server api, just create a `.env` file for your server-side api. Then run `npm run serve`

**Comment by lixaotec** [comment]
Dear @aurovrata , @wxs77577 ,

What would you suggest as technologies for API layer? 

What would fit to allow less code in order to have CRUD operations with a database, taking resources definition in account? Something to write validations and business rules.

Thank you.
