### ISSUE TITLE
Vuex-router-sync question

### ISSUE THREAD

**Issue by lixaotec** [wxs77577/rest-admin#23]
Dear friend,

What is the importance if the package vuex-router-sync? Is it really matter?

Im trying to run the solution at browser without webpack, and im finding some trouble with it. First because this package doesnt have a module that works woth browser only.

Just wondering what it does. Ive managed to run many things already but some mutations seems not to work without this package.

Buttons actions doesn’t happens , but i dont know for sure why

**Comment by wxs77577** [comment]
It's been used in Vuex stores. e.g: 
https://github.com/wxs77577/rest-admin/blob/master/src/store/modules/site.js#L60

**Comment by lixaotec** [comment]
Thanks.

I´ve accomplish by using rollit with vuex-router-sync package.
