### ISSUE TITLE
Layout Feature from configs

### ISSUE THREAD

**Issue by lixaotec** [wxs77577/rest-admin#25]
Dear,

I´ve noticed a layout props expected at formbuilder.

Can you provide more info or example on its usage.

I would like to know its 'usage' level as well, if youcan provide please.

As far as I could get, it awaits a layout info from resource/form api response.

**Comment by wxs77577** [comment]
FormBuilder is a core component of rest-admin, you can build a form by provide a `fields` property. I'm considering to split it as a package.
