### ISSUE TITLE
npm run local cause error

### ISSUE THREAD

**Issue by vlwq** [wxs77577/rest-admin#4]
1、npm run local,it cause error , but run dev success(change the config)

2、detail
```
package.js :  "local": "API_URI=http://localhost:8088/admin/api/ npm run dev",

dev.env.js.js : API_URI: `"${process.env.API_URI || 'http://192.168.50.57:5555/admin/api/'}"`
```
when npm run local, process.env.API_URI cannot get the value of API_URI

**Comment by vlwq** [comment]
闲的可以再看看了。大概看明白怎么用。有个问题，products页面，那个单选框，切换选项后没有发送请求，需要点一下搜索。。。。这是前端的那个双向绑定问题没做？，不是很懂。

**Comment by wxs77577** [comment]
那个单选框只是切换一个属性值，并没有自动发送HTTP请求，要点右上角保存

**Comment by tongxiaofeng** [comment]
Run "npm run serve" instead.
